<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ReiseArbeitszeitApp</RootNamespace>
    <AssemblyName>ReiseArbeitszeitApp.Core</AssemblyName>
    <Version>0.2.3</Version>
  </PropertyGroup>
</Project>
